export const MENU_CATEGORIES_FETCH_SUCCESS = 'MENU_CATEGORIES_FETCH_SUCCESS';
export const MENU_CATEGORIES_ADD_SUCCESS = 'MENU_CATEGORIES_ADD_SUCCESS';
export const MENU_CATEGORIES_DELETE_SUCCESS = 'MENU_CATEGORIES_DELETE_SUCCESS';
export const MENU_CATEGORIES_UPDATE_SUCCESS = 'MENU_CATEGORIES_UPDATE_SUCCESS';
export const MENU_CATEGORY_DISHES_FETCH_SUCCESS = 'MENU_CATEGORY_DISHES_FETCH_SUCCESS';
export const MENU_CATEGORY_DISHES_ADD_SUCCESS = 'MENU_CATEGORY_DISHES_ADD_SUCCESS';
export const MENU_CATEGORY_DISHES_DELETE_SUCCESS = 'MENU_CATEGORY_DISHES_DELETE_SUCCESS';
export const MENU_CATEGORY_DISHES_UPDATE_SUCCESS = 'MENU_CATEGORY_DISHES_UPDATE_SUCCESS';